services:
  - type: web
    name: rohan-raut-portfolio
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
